"""HelpNode - Documentation node generated by .help().

This module provides help system support for context nodes, allowing
agents to query documentation for any node type.
"""

from __future__ import annotations

import inspect
import re
import sys
import time
from dataclasses import dataclass, field
from typing import Any

from activecontext.context.exposed import get_exposed
from activecontext.context.graph import LinkedChildOrder
from activecontext.context.state import Expansion, TickFrequency
from activecontext.context.traceable import trace_all_fields

from .base import ContextNode


def _extract_help_content(cls: type) -> str:
    """Extract documentation from a ContextNode subclass.

    Parses class docstrings, method signatures, @exposed members, and
    properties to produce structured help content.

    For plugin node types, documentation is extracted in priority order:
    1. Explicit plugin_info dict in the module
    2. Class docstring
    3. Method docstrings for Render*, GetDigest, etc.

    Args:
        cls: The ContextNode subclass to document.

    Returns:
        Formatted help text string.
    """
    lines: list[str] = []

    # Try to get plugin_info dict from the class's module (for plugin nodes)
    plugin_info: dict[str, str] | None = None
    try:
        module = sys.modules.get(cls.__module__)
        if module is not None:
            plugin_info_dict = getattr(module, "plugin_info", None)
            if isinstance(plugin_info_dict, dict):
                plugin_info = plugin_info_dict
    except Exception:
        pass

    # Type name and description from plugin_info or docstring
    if plugin_info:
        # Use plugin_info as priority source
        plugin_name = plugin_info.get("name", cls.__name__)
        description = plugin_info.get("description")

        # If description is missing from plugin_info, fall back to docstring
        if not description:
            cls_doc = inspect.getdoc(cls) or ""
            description = cls_doc.split("\n")[0] if cls_doc else "(no description)"

        lines.append(f"# {plugin_name}")
        lines.append(f"{description}")
        lines.append("")

        # Add plugin metadata if available
        version = plugin_info.get("version")
        author = plugin_info.get("author")
        if version or author:
            lines.append("## Plugin Information")
            if version:
                lines.append(f"- **Version**: {version}")
            if author:
                lines.append(f"- **Author**: {author}")
            lines.append("")
    else:
        # Fallback to class docstring
        cls_doc = inspect.getdoc(cls) or ""
        first_line = cls_doc.split("\n")[0] if cls_doc else "(no description)"
        lines.append(f"# {cls.__name__}")
        lines.append(f"{first_line}")
        lines.append("")

    # Constructor parameters (from dataclass fields)
    try:
        from dataclasses import MISSING
        from dataclasses import fields as dc_fields

        cls_fields = dc_fields(cls)
        if cls_fields:
            lines.append("## Constructor Parameters")
            for f in cls_fields:
                if f.name.startswith("_"):
                    continue
                # Skip inherited ContextNode base fields for brevity
                if f.name in {
                    "node_id",
                    "parent_ids",
                    "child_order",
                    "expansion",
                    "mode",
                    "tick_frequency",
                    "version",
                    "created_at",
                    "updated_at",
                    "originator",
                    "title",
                    "display_sequence",
                    "content_id",
                    "notification_level",
                    "is_subscription_point",
                    "tracing",
                    "trace_sink",
                }:
                    continue
                type_str = str(f.type) if f.type else "Any"
                default_str = ""
                if f.default is not MISSING:
                    default_str = f" = {f.default!r}"
                elif f.default_factory is not MISSING:
                    default_str = " = ..."
                lines.append(f"- **{f.name}**: `{type_str}`{default_str}")
            lines.append("")
    except TypeError:
        pass

    # Exposed members
    exposed_names = get_exposed(cls)

    # Public methods (including exposed)
    methods: list[tuple[str, str, str]] = []  # (name, signature, docstring)
    properties: list[tuple[str, str, bool]] = []  # (name, docstring, writable)

    for name in sorted(dir(cls)):
        if name.startswith("_"):
            continue

        # Check via class __dict__ to find descriptors properly
        member = None
        for klass in cls.__mro__:
            if name in klass.__dict__:
                member = klass.__dict__[name]
                break
        if member is None:
            member = getattr(cls, name, None)
        if member is None:
            continue

        # Properties
        if isinstance(member, property):
            doc = inspect.getdoc(member.fget) if member.fget else ""
            first_doc = (doc or "").split("\n")[0]
            writable = member.fset is not None
            properties.append((name, first_doc, writable))
            continue

        # Regular methods
        if callable(member) and not isinstance(member, type):
            try:
                sig = inspect.signature(member)
                sig_str = str(sig)
            except (ValueError, TypeError):
                sig_str = "(...)"
            doc = inspect.getdoc(member) or ""
            first_doc = doc.split("\n")[0]
            is_exp = name in exposed_names
            marker = " *" if is_exp else ""
            methods.append((name, sig_str, first_doc + marker))

    if methods:
        lines.append("## Methods")
        for name, sig_str_display, doc in methods:
            lines.append(f"- `{name}{sig_str_display}` -- {doc}")
        lines.append("")

    if properties:
        lines.append("## Properties")
        for name, doc, writable in properties:
            rw = "read/write" if writable else "read-only"
            lines.append(f"- `{name}` ({rw}) -- {doc}")
        lines.append("")

    if exposed_names:
        lines.append("## Agent-Facing API (@exposed)")
        for name in sorted(exposed_names):
            lines.append(f"- {name}")
        lines.append("")

    return "\n".join(lines)


@trace_all_fields
@dataclass(kw_only=True)
class HelpNode(ContextNode):
    """Documentation node generated by .help().

    HelpNode renders API documentation for a specific node type. It is
    created as a child of the node being documented and provides three
    rendering levels: collapsed (brief header), summary (overview +
    method list), and detail (full documentation with signatures).

    Attributes:
        parent_node_type: The node_type string of the documented node type.
    """

    parent_node_type: str = ""
    _help_content: str = field(default="", repr=False)

    def _count_methods(self) -> int:
        """Count documented methods from help content.

        Matches lines in the Methods section that look like function signatures:
        ``- `name(`` pattern (backtick-name-open-paren).
        """
        count = 0
        in_methods = False
        for line in self._help_content.split("\n"):
            if line.startswith("## Methods"):
                in_methods = True
                continue
            if line.startswith("## ") and in_methods:
                in_methods = False
                continue
            if in_methods and re.match(r"^- `\w+\(", line):
                count += 1
        return count

    def GetDigest(self) -> dict[str, Any]:
        return {
            "id": self.node_id,
            "type": self.node_type,
            "parent_node_type": self.parent_node_type,
            "methods": self._count_methods(),
            "expansion": self.default_expansion.value,
        }

    def render_digest(self) -> str:
        """Return display name with method count."""
        methods = self._count_methods()
        return f"{self.parent_node_type} Help -- {methods} methods"

    def render_content(self) -> str:
        """Render full documentation."""
        parts: list[str] = []
        for line in self._help_content.split("\n"):
            parts.append(f"  {line}\n")
        return "".join(parts)

    def to_dict(self) -> dict[str, Any]:
        """Serialize HelpNode to dict."""
        data = super().to_dict()
        data.update(
            {
                "parent_node_type": self.parent_node_type,
                "_help_content": self._help_content,
            }
        )
        return data

    @classmethod
    def _from_dict(cls, data: dict[str, Any]) -> HelpNode:
        """Deserialize HelpNode from dict."""
        tick_freq = None
        if data.get("tick_frequency"):
            tick_freq = TickFrequency.from_dict(data["tick_frequency"])

        return cls(
            node_id=data["node_id"],
            parent_ids=set(data.get("parent_ids", [])),
            child_order=LinkedChildOrder.from_list(
                data.get("child_order") or data.get("children_ids") or []
            ),
            default_expansion=Expansion(data.get("expansion", "content")),
            mode=data.get("mode", "paused"),
            tick_frequency=tick_freq,
            version=data.get("version", 0),
            created_at=data.get("created_at", time.time()),
            updated_at=data.get("updated_at", time.time()),
            display_sequence=data.get("display_sequence"),
            originator=data.get("originator"),
            title=data.get("title", ""),
            parent_node_type=data.get("parent_node_type", ""),
            _help_content=data.get("_help_content", ""),
        )
